runtime: php73

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:z7dSgHaELg9dwATMOwbpD6BYHgsF9X4URdVFG5SB73A=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie